spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:clean-architecture-db
    username: clean-architecture-db-username
    password: clean-architecture-db-password
  jpa:
  hibernate:
  ddl-auto: create-drop
  show-sql: true
  format_sql: true
  open-in-view: false
  h2:
  console:
  enabled: true
  flyway:
    enabled: false
path: /h2