spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: false
